# docker-compose.yml example structure
version: '3.8'

services:
  ollama:
    build: ./ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 16G

  chromadb:
    # image: ghcr.io/chroma-core/chroma:latest # Build from local Dockerfile instead
    build: ./chromadb
    volumes:
      - chroma_data:/data
    environment:
      - CHROMA_DB_IMPL=duckdb+parquet
      # Add ANONYMIZED_TELEMETRY=False if you want to disable telemetry
      # - ANONYMIZED_TELEMETRY=False 
    ports:
      - "8000:8000"
    restart: unless-stopped

  backend:
    build: ./backend
    depends_on:
      ollama: 
        condition: service_started
      chromadb:
        condition: service_started
    volumes:
      - ./data:/app/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=8000
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:5000
    depends_on:
      backend:
        condition: service_started
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  ollama_data:
  chroma_data: